# Generated by Django 2.1.5 on 2019-01-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('life_assureddetails', models.CharField(max_length=50)),
                ('payment_information', models.IntegerField()),
                ('premium_details', models.IntegerField()),
            ],
        ),
    ]
