# Generated by Django 2.1.5 on 2019-01-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=500)),
                ('policyNo', models.CharField(max_length=8)),
                ('typeOfClaim', models.CharField(choices=[('car', 'Car Claim'), ('home', 'Home Claim'), ('health', 'Health Claim')], default='', max_length=6)),
                ('details', models.CharField(max_length=500)),
                ('docs', models.FileField(upload_to='')),
            ],
        ),
    ]
