# Generated by Django 2.1.5 on 2019-01-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_remove_list_docs'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='status',
            field=models.CharField(default='', max_length=500),
        ),
    ]
